export const EVENTS_UPSERT = 'EVENTS_UPSERT';
export const EVENTS_FETCH = 'EVENTS_FETCH';
export const EVENT_FAVORITE_TOGGLE = 'EVENT_FAVORITE_TOGGLE';
export const EVENT_COEFFICIENT_TOGGLE = 'EVENT_COEFFICIENT_TOGGLE';
export const EVENT_UPSERT = 'EVENT_UPSERT';
export const EVENT_UPDATE = 'EVENT_UPDATE';
export const EVENT_CREATE = 'EVENT_CREATE';
